#!/usr/bin/env bash

# Returns domain part
# It splits current directory and get the most child domain
# example1.dev => example1
# foo.bar.domain => foo
function get_domain() {
  local PWD=`pwd`
  local DOMAIN=${PWD##*/}
  local IFS='.'
  set -- ${DOMAIN}
  echo $1
}

function create_database() {
  CMD="mysqladmin create -u${DB_USER} -p${DB_PASS} ${DB_NAME}"
  echo $CMD
}

# if DB_NAME is not set, returns DB_USER + DOMAIN
#
#
function get_dbname() {
  if [ -z "${DB_NAME}" ]; then
   DB_NAME=${DB_USER}_$1
  fi
  echo $DB_NAME
}

domain=`get_domain`
echo $domain
DB_NAME=`get_dbname $domain`
echo $DB_NAME

create_database

exit 0;





exit;

#wp core download --locale=ja

#wp core config \
   --dbname=${DB_NAME} \
   --dbuser=${DB_USER} \
   --dbpass=${DB_PASS} \
   --dbhost=${DB_HOST} \
   --dbprefix=${PREFIX} \
   --extra-php <<PHP
    define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', true );
    define( 'FS_METHOD', 'direct' );
PHP

#

export DOMAIN=forced.l2tp.org
wp core install \
   --url=${DOMAIN} \
   --title=${DOMAIN} \
   --admin_user=${WP_USER} \
   --admin_password=${WP_PASS} \
   --admin_email=${WP_MAIL}

wp core language install ja --activate
#
wp plugin install \
   add-page-from-template \
   advanced-custom-fields \
   backwpup \
   custom-post-type-permalinks \
   custom-post-type-ui \
   debug-bar \
   debug-bar-console \
   duplicate-post \
   fg-debug-bar-rewrite-rules \
   post-type-switcher \
   show-current-template \
   --activate
#
#wp rewrite structure '/archives/%post_id%'
#
#wp scaffold child-theme twentysixteen-child --parent_theme=twentysixteen
#wp theme activate twentysixteen-child
