#!/usr/bin/env bash

# Returns domain part
# It splits current directory and get the most child domain
# example1.dev => example1
# foo.bar.domain => foo

function get_slug() {
  local PWD=`pwd`
  DOMAIN=${PWD##*/}
  local IFS='.'
  set -- ${DOMAIN}
  echo $1
}

function get_domain() {
  local PWD=`pwd`
  DOMAIN=${PWD##*/}
  echo ${DOMAIN}
}

function create_database() {
  echo 'CREATE DATABASE '${DB_NAME}';' | MYSQL_PWD=${DB_PASS} mysql -h ${DB_HOST} -u ${DB_USER}
}

function drop_database() {
  # @link http://qiita.com/e_tei/items/bbfc90bfae28799d2176
  echo 'DROP DATABASE IF EXISTS '${DB_NAME}';' | MYSQL_PWD=${DB_PASS} mysql -h ${DB_HOST} -u ${DB_USER}
}

# if DB_NAME is not set, returns DB_USER + DOMAIN
#
#
function get_dbname() {
  if [ -z "${DB_NAME}" ]; then
   DB_NAME=${DB_USER}_$1
  fi
  echo $DB_NAME
}

function wp_download() {
  wp core download --locale=ja
}

function wp_config() {
  wp core config \
     --dbname=${DB_NAME} \
     --dbuser=${DB_USER} \
     --dbpass=${DB_PASS} \
     --dbhost=${DB_HOST} \
     --dbprefix=${WP_PREFIX} \
     --extra-php <<PHP
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'FS_METHOD', 'direct' );
PHP
}

function wp_install() {
  wp core install \
     --url=${DOMAIN} \
     --title=${DOMAIN} \
     --admin_user=${WP_USER} \
     --admin_password=${WP_PASS} \
     --admin_email=${WP_MAIL}
}

function wp_plugin() {
  wp plugin install \
   add-page-from-template \
   advanced-custom-fields \
   backwpup \
   custom-post-type-permalinks \
   custom-post-type-ui \
   debug-bar \
   debug-bar-console \
   duplicate-post \
   fg-debug-bar-rewrite-rules \
   post-type-switcher \
   show-current-template \
   --activate
}

function source_env() {
 if [ -f .env ]; then
   source .env
# else if [ -f .htenv ]; then
#   source ./.htenv
 else
   echo 'Error: .env or .htenv file not found.'
   exit 1
 fi
}

source_env
SLUG=`get_slug`
DOMAIN=`get_domain`
echo 'Setting domain as '$DOMAIN
DB_NAME=`get_dbname $SLUG`
echo 'Installing into '$DB_NAME' Database.'

drop_database
create_database
wp_download
wp_config
wp_install

# wp_plugin

exit 0;

#  wp core language install ja --activate
#wp core language install ja --activate
#
#wp rewrite structure '/archives/%post_id%'
#
#wp scaffold child-theme twentysixteen-child --parent_theme=twentysixteen
#wp theme activate twentysixteen-child
